#
# SPDX-FileCopyrightText: 2022 Wesley Schwengle <wesley@opperschaap.net>
#
# SPDX-License-Identifier: BSD-3-Clause
#
version: '3.6'
services:
  connectiq:
    image: connectiq-sdk:latest
    volumes:
      - /tmp/.X11-unix:/tmp/.X11-unix
      - $HOME/.Xauthority:/home/ciq/.Xauthority:ro
      - $HOME/.Garmin/ConnectIQ:/home/ciq/.Garmin/ConnectIQ
      - $HOME/garmin:/mnt/garmin:rw
      - ./:/home/ciq/src
    environment:
      DISPLAY: $DISPLAY
      XAUTHORITY: /home/ciq/.Xauthority
      CIQ_DEVICE: fenix6
      MY_PROJECT: Semicircles
      CIQ_API: 3.2.6
      CIQ_TYPECHECK: 0

networks:
  default:
